language: python
python:
 - 2.7
env:
  matrix:
   - PLONE_VERSION=4.2
   - PLONE_VERSION=4.3
   - PLONE_VERSION=5.0
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap-buildout.py
  - bin/buildout -N -t 3 -c "travis-$PLONE_VERSION.x.cfg"

script: bin/test
